# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"

reviews:
  profile: "chill"
  request_changes_workflow: false

  auto_review:
    enabled: true
    drafts: false
    # Because your default branch is working_branch, add main here:
    base_branches:
      - "^main$"